
-- CONFIG_DEFAULT_EXCLUDE_START
Config.PhoneConfigurator = {
    Enabled = true,
}

Config.CommandPermissions = {
    phonepanel = { "god", "superadmin", "admin" },
    phonetestdata = { "god", "superadmin", "admin" },
    fliptokverify = { "god", "superadmin", "admin" },
    picstagramverify = { "god", "superadmin", "admin" },
    picstagramadmin = { "god", "superadmin", "admin" },
}
-- CONFIG_DEFAULT_EXCLUDE_END
Config.Bridge = {
    Framework = "auto",
    Inventory = "auto",
    Locale = "fr",
    CallbackTimeout = 15000,
    Debug = false,
}

Config.Command = "phone"
Config.Phone = {
    Item = "phone",
    Unique = true,
    Keybind = "F1",
    OpenRequestsPerMinute = 20,
    AllowMovement = true,
    HoldToLook = {
        Enabled = true,
        Control = 19,
    },
    DevelopmentCommand = true,
    DeviceName = "iFruit Phone",
}
Config.Apps = {
    ["app-store"] = true,
    banking = true,
    billing = true,
    calculator = true,
    calendar = true,
    camera = true,
    citymarkt = true,
    clock = true,
    companies = true,
    darkchat = true,
    feather = true,
    flare = true,
    fliptok = true,
    garage = true,
    mail = true,
    map = true,
    memos = true,
    messages = true,
    music = true,
    notes = true,
    ["number-merge"] = true,
    phone = true,
    photos = true,
    picstagram = true,
    settings = true,
    ["agent-flappy"] = true,
    agentride = true,
    snake = true,
    weather = true,
}
Config.TestData = {
    Enabled = false,
    Command = "phonetestdata",
    AdminOnly = false,
}
Config.CustomApps = {
    Enabled = true,
    BundledApps = true,
    ExternalApps = true,
    Debug = false,
    ReadyTimeoutMs = 8000,
    MaximumMessageBytes = 65536,
    MaximumStorageBytesPerApp = 262144,
    MaximumStorageValueBytes = 65536,
    MaximumStorageKeyLength = 64,
    MaximumStorageKeysPerApp = 128,
    StorageRequestsPerMinute = 120,
    TrustedAdapters = {},
}
Config.Security = {
    MaximumAttempts = 5,
    LockSeconds = 30,
    AttemptsPerMinute = 12,
}
Config.AdminPanel = {
    Enabled = true,
    Command = "phonepanel",
    MaximumPlayers = 128,
    ReadRequestsPerMinute = 60,
    ActionRequestsPerMinute = 30,
    CredentialRevealsPerMinute = 6,
    AuditLimit = 40,
    ActivityLimit = 40,
}
Config.Sim = {
    Enabled = true,
    RegisteredItem = "agent_phone_sim_registered",
    AnonymousItem = "agent_phone_sim_anonymous",
    NumberLength = 10,
    NumberPrefix = "",
    NumberGroups = { 3, 3, 4 },
}

Config.Speaker = {
    Enabled = true,
}
Config.Calls = {
    VoiceProvider = "pma",
    RingSeconds = 30,
    ContactNameMaxLength = 80,
    ContactNotesMaxLength = 500,
    RecentPageSize = 100,
}
Config.Payphones = {
    Enabled = true,
    Props = {
        "prop_phonebox_01b",
        "p_phonebox_01b_s",
        "prop_phonebox_01a",
        "prop_phonebox_04",
    },

    CustomProp = "prop_phonebox_01b",
    CustomLocations = {
    },
    ReplacementProp = "sf_prop_sf_phonebox_01b_s",
    PricePerSecond = 1,
    PaymentAccount = "cash",
    Currency = "$",
    NoAnswerTimeoutSeconds = 30,
    CallerNumber = "PAYPHONE",
    InteractionDistance = 1.8,
    ServerValidationDistance = 3.0,
    MaximumCallDistance = 4.0,
    ScanDistance = 25.0,
    ScanIntervalMs = 1000,
    ModelLoadTimeoutMs = 5000,
    Animation = {
        Dictionary = "anim@scripted@payphone_hits@male@",
        PedClip = "FXFR_PAV_1_INTRO_MALE",
        PropClip = "FXFR_PAV_1_INTRO_PHONE",
        HangupDurationMs = 2000,
    },
}
Config.Animations = {
    Enabled = true,
    PropModel = "prop_npc_phone_02",
    PropBone = 28422,
    LoadTimeoutMs = 5000,
    ContextPollMs = 250,
    Dictionaries = {
        OnFoot = "cellphone@",
        Driver = "anim@cellphone@in_car@ds",
        Passenger = "anim@cellphone@in_car@ps",
        Camera = "cellphone@self",
    },
    Clips = {
        TextIn = "cellphone_text_in",
        TextRead = "cellphone_text_read_base",
        TextOut = "cellphone_text_out",
        TextToCall = "cellphone_text_to_call",
        CallListen = "cellphone_call_listen_base",
        CallToText = "cellphone_call_to_text",
        CallOut = "cellphone_call_out",
        Camera = "selfie",
    },
    Transforms = {
        Portrait = {
            position = vector3(0.0, 0.0, 0.0),
            rotation = vector3(0.0, 0.0, 0.0),
        },
        Landscape = {
            position = vector3(0.0, 0.0, 0.0),
            rotation = vector3(0.0, 0.0, 90.0),
        },
    },
}
Config.Messages = {
    BodyMaxLength = 2000,
    ConversationScanLimit = 1000,
    ThreadPageSize = 200,
    SendsPerMinute = 30,
    MediaLoadsPerMinute = 120,
    VoiceMaxDurationMs = 30000,
    VoiceMaxBase64Length = 180000,
    VoiceWaveformSamples = 48,
    VideoMaxDurationMs = 30000,
    DeleteBatchSize = 20,
}
Config.Memos = {
    MaximumCount = 100,
    MaximumDurationMs = 300000,
    MaximumBytes = 2 * 1024 * 1024,
    MaximumWaveformSamples = 96,
    TitleMaxLength = 120,
    NoteMaxLength = 2000,
    UploadsPerMinute = 10,
    WritesPerMinute = 60,
    ListsPerMinute = 60,
    MaximumPendingUploads = 1,
    UploadSessionTimeoutMs = 60000,
}
Config.EasyShare = {
    Enabled = true,
    DefaultVisibility = "everyone",
    MaximumDistance = 15.0,
    HistoryLimit = 50,
    PendingSeconds = 30,
    TransferDurationMs = 3000,
    RequestsPerMinute = 12,
    BootstrapRequestsPerMinute = 30,
    VisibilityUpdatesPerMinute = 10,
    ActionsPerMinute = 30,
    PayloadMaxBytes = 24000,
}
Config.DarkChat = {
    AliasMaxLength = 32,
    BodyMaxLength = 2000,
    ThreadPageSize = 200,
    SendsPerMinute = 30,
    ActionsPerMinute = 60,
    ReportsPerDay = 10,
    VoiceMaxDurationMs = 60000,
    VoiceMaxBase64Length = 360000,
    VoiceWaveformSamples = 48,
    CleanupIntervalSeconds = 30,
    CleanupBatchSize = 250,
    AllowedDisappearTimers = {
        [0] = true,
        [-1] = true,
        [60] = true,
        [300] = true,
        [3600] = true,
        [86400] = true,
        [604800] = true,
    },
}
Config.Mail = {
    Domain = "ifruit.com",
    LocalPartMinLength = 3,
    LocalPartMaxLength = 32,
    PasswordMinLength = 6,
    PasswordMaxLength = 64,
    SubjectMaxLength = 120,
    BodyMaxLength = 20000,
    MaxRecipients = 10,
    PageSize = 50,
    AuthAttemptsPerMinute = 5,
    MailboxNameMaxLength = 50,
    MaxMailboxes = 20,
    MailboxRequestsPerMinute = 12,
    DeleteBatchSize = 50,
    DeleteRequestsPerMinute = 12,
}
Config.Banking = {
    Currency = "$",
    MinimumAmount = 1,
    MaximumAmount = 1000000,
    ActionsPerMinute = 12,
    HistoryLimit = 50,
}
Config.Billing = {
    Enabled = true,
    Currency = "$",
    PaymentAccount = "bank",
    MinimumAmount = 1,
    MaximumAmount = 1000000,
    PageSize = 30,
    UrgentLimit = 5,
    ActionsPerMinute = 8,
    AllowDisputes = true,
    DefaultDueDays = 7,
    MaximumTitleLength = 160,
    MaximumDescriptionLength = 1000,
}
Config.Garage = {
    System = "auto",
    MaximumVehicles = 250,
    RequestsPerMinute = 30,
    VehicleImages = {
        Enabled = true,
        UrlTemplate = "https://docs.fivem.net/vehicles/{model}.webp",
        ModelNames = {},
    },
    Custom = {
        Table = "",
        OwnerColumn = "",
    },
    Valet = {
        Enabled = true,
        Price = 750,
        Account = "bank",
        RequestsPerMinute = 3,
        CooldownSeconds = 60,
        TimeoutSeconds = 180,
        SpawnDistance = 110.0,
        ArrivalDistance = 14.0,
        DriveSpeed = 20.0,
        DrivingStyle = 786603,
        DriverModel = "s_m_m_autoshop_01",
        VehicleTypes = {
            car = true,
            bike = true,
            boat = false,
            plane = false,
            helicopter = false,
        },
    },
}
Config.Marketplace = {
    PageSize = 20,
    MessagePageSize = 50,
    OfferHistorySize = 50,
    MaxActiveListings = 15,
    MaxImages = 6,
    TitleMinLength = 5,
    TitleMaxLength = 70,
    DescriptionMinLength = 20,
    DescriptionMaxLength = 2000,
    MessageMaxLength = 1000,
    MaximumPrice = 100000000,
    ListingLifetimeDays = 7,
    Categories = {
        "vehicles",
        "property",
        "electronics",
        "clothing",
        "tools",
        "leisure",
        "services",
        "jobs",
        "wanted",
        "other",
    },
    Districts = {
        "los_santos",
        "vinewood",
        "vespucci",
        "south_los_santos",
        "sandy_shores",
        "paleto_bay",
        "blaine_county",
    },
    PhotoGradients = {
        "linear-gradient(145deg, #ff9a62, #5f2c82 58%, #141e30)",
        "linear-gradient(160deg, #67d5b5, #26648e 55%, #0b132b)",
        "linear-gradient(135deg, #fbc2eb, #a6c1ee 48%, #302b63)",
        "linear-gradient(150deg, #f6d365, #fda085 45%, #512b58)",
        "linear-gradient(145deg, #ff6b6b, #845ec2 52%, #0f2027)",
        "linear-gradient(150deg, #00c9a7, #4d8076 46%, #1f3a5f)",
        "linear-gradient(135deg, #ffc75f, #f96d80 48%, #4b4453)",
    },
}
Config.FlipTok = {
    PageSize = 12,
    CaptionMaxLength = 500,
    CommentMaxLength = 300,
    BioMaxLength = 160,
    PasswordMinLength = 8,
    PasswordMaxLength = 72,
    MaxVideoDurationMs = 300000,
    MaxPostMedia = 10,
    MusicTracks = {},
    VerifyCommand = "fliptokverify",
    ReportWebhookConvar = "agent_phone_fliptok_report_webhook",
}
Config.Picstagram = {
    PageSize = 12,
    CommentPageSize = 100,
    MaxPostMedia = 5,
    CaptionMaxLength = 800,
    CommentMaxLength = 300,
    BioMaxLength = 160,
    LocationMaxLength = 80,
    StoryTextMaxLength = 160,
    StoryLifetimeSeconds = 24 * 60 * 60,
    PasswordMinLength = 8,
    PasswordMaxLength = 72,
    PostsPerMinute = 6,
    StoriesPerMinute = 6,
    CommentsPerMinute = 20,
    ReportDetailsMaxLength = 500,
    ReportReasons = { "spam", "harassment", "dangerous", "illegal", "other" },
    VerifyCommand = "picstagramverify",
}
Config.Feather = {
    PageSize = 20,
    TextMaxLength = 360,
    BioMaxLength = 160,
    DisplayNameMaxLength = 50,
    HandleMaxLength = 30,
    SearchMaxLength = 80,
    HashtagMaxLength = 64,
    TrendingTopicLimit = 10,
    ReportDetailsMaxLength = 500,
    MaxImages = 4,
    PostsPerMinute = 8,
    ActionsPerMinute = 90,
    ReportsPerDay = 10,
}
Config.MapMarkers = {
    MaximumMarkers = 50,
    LabelMaxLength = 40,
    ActionsPerMinute = 60,
}

Config.Calendar = {
    TitleMaxLength = 120,
    NoteMaxLength = 2000,
    MaximumDurationSeconds = 7 * 24 * 60 * 60,
    MaximumQuerySeconds = 370 * 24 * 60 * 60,
    PastEditSeconds = 365 * 24 * 60 * 60,
    FutureSeconds = 5 * 365 * 24 * 60 * 60,
    ReminderPollSeconds = 15,
}

Config.AgentRide = {
    PaymentAccount = "bank",
    Currency = "$",
    ProfileNameMinLength = 2,
    ProfileNameMaxLength = 50,
    DistanceUnit = "kilometer",
    QuoteLifetimeSeconds = 120,
    HistoryLimit = 50,
    ReadsPerMinute = 120,
    ActionsPerMinute = 30,
    QuotesPerMinute = 20,
    RecoveryIntervalSeconds = 15,
    PaymentPendingRecoverySeconds = 30,
    PickupSelectionRadius = 150.0,
    ArrivalRadius = 40.0,
    CompletionRadius = 80.0,
    MinimumDistanceMeters = 250,
    MaximumDistanceMeters = 40000,
    RouteDistanceMultiplier = 1.25,
    AverageSpeedMetersPerSecond = 12.0,
    DriverPayoutPercent = 85,
    RatingCommentMaxLength = 300,
    MaximumTip = 10000,
    CustomFare = {
        Enabled = true,
        MinimumPrice = 5,
        MaximumPrice = 100000,
        MinimumCalculatedMultiplier = 0.5,
        MaximumCalculatedMultiplier = 3.0,
    },
    DriverJobs = {
        taxi = 0,
    },
    Services = {
        {
            Id = "taxi",
            Seats = 4,
            EtaMinutes = 3,
            BaseFare = 12,
            PricePerKilometer = 18,
            PricePerMile = 29,
            PricePerMinute = 1,
            MinimumFare = 15,
        },
        {
            Id = "comfort",
            Seats = 4,
            EtaMinutes = 5,
            BaseFare = 16,
            PricePerKilometer = 24,
            PricePerMile = 39,
            PricePerMinute = 2,
            MinimumFare = 22,
        },
        {
            Id = "xl",
            Seats = 6,
            EtaMinutes = 7,
            BaseFare = 20,
            PricePerKilometer = 30,
            PricePerMile = 48,
            PricePerMinute = 2,
            MinimumFare = 28,
        },
        {
            Id = "premium",
            Seats = 4,
            EtaMinutes = 8,
            BaseFare = 28,
            PricePerKilometer = 40,
            PricePerMile = 64,
            PricePerMinute = 3,
            MinimumFare = 38,
        },
    },
    QuickLocations = {
        {
            Id = "legion-square",
            Label = "Legion Square",
            Coords = vector3(-265.1, -960.2, 31.2),
        },
        {
            Id = "diamond-casino",
            Label = "Diamond Casino",
            Coords = vector3(925.2, 46.4, 81.1),
        },
        {
            Id = "airport",
            Label = "Los Santos Airport",
            Coords = vector3(-1037.7, -2737.8, 20.2),
        },
        {
            Id = "vinewood",
            Label = "Vinewood",
            Coords = vector3(-594.4, -929.9, 23.9),
        },
    },
}
if IsDuplicityVersion() then

    Config.Server = {
        PasscodePepper = "",
        FlipTokPasswordPepper = "",
        PicstagramPasswordPepper = "",
    }
    Config.Companies = {
        Enabled = true,
        PageSize = 20,
        MaximumPageSize = 50,
        MaximumOpenRequestsPerSim = 5,
        MaximumServices = 25,
        MaximumRequestMedia = 3,
        SubjectMaxLength = 120,
        RequestBodyMaxLength = 2000,
        MessageMaxLength = 2000,
        ProfileDescriptionMaxLength = 1000,
        DistrictMaxLength = 80,
        AddressMaxLength = 160,
        ServiceTitleMaxLength = 80,
        ServiceDescriptionMaxLength = 500,
        ServicePriceMaxLength = 80,
        AnnouncementTitleMaxLength = 120,
        AnnouncementBodyMaxLength = 1000,
        AvailabilityMaximumSeconds = 24 * 60 * 60,
        AnnouncementMaximumSeconds = 30 * 24 * 60 * 60,
        RetentionDays = 180,
        RateLimits = {
            Read = 120,
            Search = 60,
            CreateRequest = 5,
            Message = 30,
            RequestAction = 30,
            Profile = 12,
            CallAvailability = 30,
        },
        CallRouting = {
            MaxAttempts = 3,
            RingSeconds = 10,
        },
        Categories = {
            "public_services",
            "vehicles",
            "transport",
        },
        Statuses = {
            new = true,
            assigned = true,
            in_progress = true,
            waiting_customer = true,
            completed = true,
            cancelled = true,
        },
        AvailabilityStatuses = {
            available = true,
            busy = true,
            closed = true,
        },
        Definitions = {
            police = {
                Job = "police",
                Name = "Los Santos Police Department",
                Category = "public_services",
                Public = true,
                Emergency = true,
                Verified = true,
                Icon = "shield",
                LogoUrl = "https://picsum.photos/seed/companies-police-logo/180/180",
                Description = "Public safety, emergency response, and police services.",
                DefaultAvailability = "closed",
                AcceptsRequests = true,
                District = "Mission Row",
                LocationLabel = "Mission Row Police Station",
                Address = "Mission Row Police Station",
                Location = vector3(425.1, -979.5, 30.7),
                ServiceLine = {
                    Number = "911",
                    AutoContact = true,
                    CanCall = true,
                    CanMessage = true,
                    Routing = "round_robin",
                    MinimumGrade = 0,
                },
                Permissions = {
                    WorkQueue = 0,
                    Availability = 1,
                    Assign = 2,
                    Profile = 3,
                    Hours = 3,
                    Services = 3,
                    Announcement = 3,
                },
                Services = {
                    {
                        Id = "police-assistance",
                        Title = "Police assistance",
                        Description = "Request non-emergency police assistance.",
                        Price = "",
                        RequestsEnabled = true,
                    },
                },
            },
            ambulance = {
                Job = "ambulance",
                Name = "Emergency Medical Services",
                Category = "public_services",
                Public = true,
                Emergency = true,
                Verified = true,
                Icon = "medical",
                LogoUrl = "https://picsum.photos/seed/companies-ems-logo/180/180",
                Description = "Emergency medical response and patient care.",
                DefaultAvailability = "closed",
                AcceptsRequests = false,
                District = "Pillbox Hill",
                LocationLabel = "Pillbox Hill Medical Center",
                Address = "Pillbox Hill Medical Center",
                Location = vector3(307.2, -595.3, 43.3),
                ServiceLine = {
                    Number = "912",
                    AutoContact = true,
                    CanCall = true,
                    CanMessage = false,
                    Routing = "round_robin",
                    MinimumGrade = 0,
                },
                Permissions = {
                    WorkQueue = 0,
                    Availability = 1,
                    Assign = 2,
                    Profile = 3,
                    Hours = 3,
                    Services = 3,
                    Announcement = 3,
                },
                Services = {},
            },
            fire = {
                Job = "fire",
                Name = "Los Santos Fire Department",
                Category = "public_services",
                Public = true,
                Emergency = true,
                Verified = true,
                Icon = "flame",
                LogoUrl = "https://picsum.photos/seed/companies-fire-logo/180/180",
                Description = "Fire response, rescue, and public safety services.",
                DefaultAvailability = "closed",
                AcceptsRequests = false,
                District = "El Burro Heights",
                LocationLabel = "Capital Boulevard Fire Station",
                Address = "Capital Boulevard Fire Station",
                Location = vector3(1200.6, -1473.6, 34.9),
                ServiceLine = {
                    Number = "913",
                    AutoContact = true,
                    CanCall = true,
                    CanMessage = false,
                    Routing = "round_robin",
                    MinimumGrade = 0,
                },
                Permissions = {
                    WorkQueue = 0,
                    Availability = 1,
                    Assign = 2,
                    Profile = 3,
                    Hours = 3,
                    Services = 3,
                    Announcement = 3,
                },
                Services = {},
            },
            mechanic = {
                Job = "mechanic",
                Name = "Los Santos Customs",
                Category = "vehicles",
                Public = true,
                Emergency = false,
                Verified = true,
                Icon = "wrench",
                LogoUrl = "https://picsum.photos/seed/companies-mechanic-logo/180/180",
                Description = "Vehicle diagnostics, repairs, and roadside assistance.",
                DefaultAvailability = "closed",
                AcceptsRequests = true,
                District = "Burton",
                LocationLabel = "Los Santos Customs",
                Address = "Carcer Way",
                Location = vector3(-337.3, -136.9, 39.0),
                ServiceLine = {
                    Number = "5550101000",
                    AutoContact = true,
                    CanCall = true,
                    CanMessage = false,
                    Routing = "round_robin",
                    MinimumGrade = 0,
                },
                Permissions = {
                    WorkQueue = 0,
                    Availability = 1,
                    Assign = 2,
                    Profile = 3,
                    Hours = 3,
                    Services = 3,
                    Announcement = 3,
                },
                Services = {
                    {
                        Id = "mechanic-repair",
                        Title = "Vehicle repair",
                        Description = "Diagnostics and repairs for road vehicles.",
                        Price = "Price after inspection",
                        RequestsEnabled = true,
                    },
                    {
                        Id = "mechanic-towing",
                        Title = "Roadside assistance",
                        Description = "Assistance for disabled vehicles.",
                        Price = "Price by distance",
                        RequestsEnabled = true,
                    },
                },
            },
            taxi = {
                Job = "taxi",
                Name = "Downtown Cab Co.",
                Category = "transport",
                Public = true,
                Emergency = false,
                Verified = true,
                Icon = "car",
                LogoUrl = "https://picsum.photos/seed/companies-taxi-logo/180/180",
                Description = "Staffed taxi rides throughout Los Santos and Blaine County.",
                DefaultAvailability = "closed",
                AcceptsRequests = true,
                District = "East Vinewood",
                LocationLabel = "Downtown Cab Co.",
                Address = "Tangerine Street",
                Location = vector3(895.0, -179.2, 74.7),
                ServiceLine = {
                    Number = "5550102000",
                    AutoContact = true,
                    CanCall = true,
                    CanMessage = false,
                    Routing = "round_robin",
                    MinimumGrade = 0,
                },
                Permissions = {
                    WorkQueue = 0,
                    Availability = 1,
                    Assign = 2,
                    Profile = 3,
                    Hours = 3,
                    Services = 3,
                    Announcement = 3,
                },
                Services = {
                    {
                        Id = "taxi-ride",
                        Title = "Taxi ride",
                        Description = "Request a staffed taxi service.",
                        Price = "Metered fare",
                        RequestsEnabled = true,
                    },
                },
            },
        },
    }
    Config.Music = {
        Tracks = {

        },
        MaximumPersonalSongs = 100,
        MaximumPlaylists = 50,
        MaximumPlaylistSongs = 250,
        PlaylistNameMaxLength = 80,
        ActionsPerMinute = 30,
        MetadataTimeoutMs = 4500,
    }

    Config.Migrations = Config.Migrations or {}

    Config.Migrations.LbPhone = {
        SourcePrefix = "phone_",

        IdentifierMode = "auto",
        Domains = {
            devices = true,
            settings = true,
            alarms = true,
            contacts = true,
            blocked = true,
            calls = true,
            messages = true,
            photos = true,
            notes = true,
            wallet = true,
            voiceMemos = true,
            picstagram = true,
            mail = true,
            mapMarkers = true,
            darkChat = true,
            flipTok = true,
            feather = true,
            flare = true,
        },
    }
end